### ISSUE TITLE
Documentation Refers to the Incorrect Path for PVE Autosnap

### ISSUE THREAD

**Issue by AT-StephenDetomasi** [ponceto/pve-autosnap#2]
Hi there,

I noticed that the documentation mentions that the path to pve-autosnap for crontab is "/usr/local/bin/pve-autosnap" but in reality it is "/usr/bin/pve-autosnap". Could this be updated?

**Comment by ponceto** [comment]
Hi!

You're right. I'll fix the documentation.

**Comment by ponceto** [comment]
Documentation fixed/updated. Thank you.
